services:
  CommandChainBundle\:
    resource: '../../*'
    exclude: '../../{DependencyInjection,Entity,Tests}'

  command_chain.registry:
    class: CommandChainBundle\Service\CommandChainRegistry

  CommandChainBundle\EventListener\CommandChainListener:
    arguments:
      $registry: '@command_chain.registry'
      $logger: '@logger'
    tags:
      - { name: kernel.event_listener, event: console.command, method: onConsoleCommand }