services:
  CommandChainBundle\:
    resource: '../../*'
    exclude: '../../{DependencyInjection,Entity,Tests}'

  CommandChainBundle\Service\CommandChainRegistry:
    public: true

  CommandChainBundle\EventListener\CommandChainListener:
    arguments:
      $registry: '@CommandChainBundle\Service\CommandChainRegistry'
      $logger: '@logger'
    tags:
      - { name: kernel.event_listener, event: console.command, method: onConsoleCommand }